/**
 * English translations for the Orbit app
 * Values can be:
 * - String constants for static text
 * - Functions with typed object parameters for dynamic text
 */

/**
 * English plural helper function
 * @param options - Object containing count, singular, and plural forms
 * @returns The appropriate form based on count
 */
function plural({ count, singular, plural }: { count: number; singular: string; plural: string }): string {
    return count === 1 ? singular : plural;
}

export const en = {
    tabs: {
        // Tab navigation labels
        inbox: 'Inbox',
        sessions: 'Terminals',
        settings: 'Settings',
    },

    inbox: {
        // Inbox screen
        emptyTitle: 'Empty Inbox',
        emptyDescription: 'Connect with friends to start sharing sessions',
        updates: 'Updates',
    },

    common: {
        // Simple string constants
        cancel: 'Cancel',
        authenticate: 'Authenticate',
        save: 'Save',
        saveAs: 'Save As',
        error: 'Error',
        success: 'Success',
        ok: 'OK',
        continue: 'Continue',
        back: 'Back',
        create: 'Create',
        rename: 'Rename',
        reset: 'Reset',
        logout: 'Logout',
        yes: 'Yes',
        no: 'No',
        discard: 'Discard',
        version: 'Version',
        copied: 'Copied',
        copy: 'Copy',
        scanning: 'Scanning...',
        urlPlaceholder: 'https://example.com',
        home: 'Home',
        message: 'Message',
        image: 'Image',
        attachments: 'Attachments',
        files: 'Files',
        fileViewer: 'File Viewer',
        loading: 'Loading...',
        retry: 'Retry',
        delete: 'Delete',
        optional: 'optional',
        openSettings: 'Open Settings',
        default: 'default',
    },

    profile: {
        userProfile: 'User Profile',
        details: 'Details',
        firstName: 'First Name',
        lastName: 'Last Name',
        username: 'Username',
        status: 'Status',
    },

    status: {
        connected: 'connected',
        connecting: 'connecting',
        disconnected: 'disconnected',
        error: 'error',
        online: 'online',
        offline: 'offline',
        lastSeen: ({ time }: { time: string }) => `last seen ${time}`,
        permissionRequired: 'permission required',
        activeNow: 'Active now',
        unknown: 'unknown',
    },

    sessionRun: {
        running: 'Thinking',
        connecting: 'Connecting',
        permissionRequired: 'Waiting for permission',
        reconnecting: 'Disconnected, reconnecting',
        disconnected: 'Disconnected',
        archived: 'Archived',
        stop: 'Stop',
    },

    time: {
        justNow: 'just now',
        minutesAgo: ({ count }: { count: number }) => `${count} minute${count !== 1 ? 's' : ''} ago`,
        hoursAgo: ({ count }: { count: number }) => `${count} hour${count !== 1 ? 's' : ''} ago`,
    },

    connect: {
        restoreAccount: 'Restore Account',
        enterSecretKey: 'Please enter a secret key',
        invalidSecretKey: 'Invalid secret key. Please check and try again.',
        enterUrlManually: 'Enter URL manually',
    },

    settings: {
        title: 'Settings',
        quickAccess: 'Quick access',
        connections: 'Connections',
        connectedAccounts: 'Connected Accounts',
        connectAccount: 'Connect account',
        github: 'GitHub',
        machines: 'Machines',
        manageDevices: 'Manage devices',
        deviceSummary: ({ total, online }: { total: number; online: number }) =>
            online > 0 ? `${total} devices · ${online} online` : `${total} devices`,
        aboutOrbit: 'About Orbit',
        features: 'Features',
        social: 'Social',
        account: 'Account',
        accountSubtitle: 'Manage your account details',
        appearance: 'Appearance',
        appearanceSubtitle: 'Customize how the app looks',
        voiceAssistant: 'Voice Assistant',
        voiceAssistantSubtitle: 'Configure voice interaction preferences',
        featuresTitle: 'Features',
        featuresSubtitle: 'Enable or disable app features',
        developer: 'Developer',
        developerTools: 'Developer Tools',
        about: 'About',
        aboutFooter: 'Orbit is a Codex and Claude Code mobile client. It\'s fully end-to-end encrypted and your account is stored only on your device. Not affiliated with Anthropic.',
        whatsNew: 'What\'s New',
        whatsNewSubtitle: 'See the latest updates and improvements',
        reportIssue: 'Report an Issue',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        eula: 'EULA',
        supportUs: 'Support us',
        supportUsSubtitlePro: 'Thank you for your support!',
        supportUsSubtitle: 'Support project development',
        scanQrCodeToAuthenticate: 'Scan QR code to authenticate',
        claudeAuthSuccess: 'Successfully connected to Claude',
        exchangingTokens: 'Exchanging tokens...',
        usage: 'Usage',
        usageSubtitle: 'View your API usage and costs',
        // Dynamic settings messages
        accountConnected: ({ service }: { service: string }) => `${service} account connected`,
        machineStatus: ({ name, status }: { name: string; status: 'online' | 'offline' }) =>
            `${name} is ${status}`,
        featureToggled: ({ feature, enabled }: { feature: string; enabled: boolean }) =>
            `${feature} ${enabled ? 'enabled' : 'disabled'}`,
    },

    settingsAppearance: {
        // Appearance settings screen
        theme: 'Theme',
        themeDescription: 'Choose your preferred color scheme',
        themeOptions: {
            adaptive: 'Adaptive',
            light: 'Light', 
            dark: 'Dark',
        },
        themeDescriptions: {
            adaptive: 'Match system settings',
            light: 'Always use light theme',
            dark: 'Always use dark theme',
        },
        display: 'Display',
        displayDescription: 'Control layout and spacing',
        conversation: 'Conversation',
        conversationDescription: 'How chats and session lists are presented throughout the app.',
        codeViews: 'Code Views',
        codeViewsDescription: 'How diffs and tool output are displayed while you work.',
        inlineToolCalls: 'Inline Tool Calls',
        inlineToolCallsDescription: 'Display tool calls directly in chat messages',
        expandTodoLists: 'Expand Todo Lists',
        expandTodoListsDescription: 'Show all todos instead of just changes',
        showLineNumbersInDiffs: 'Show Line Numbers in Diffs',
        showLineNumbersInDiffsDescription: 'Display line numbers in code diffs',
        showLineNumbersInToolViews: 'Show Line Numbers in Tool Views',
        showLineNumbersInToolViewsDescription: 'Display line numbers in tool view diffs',
        wrapLinesInDiffs: 'Wrap Lines in Diffs',
        wrapLinesInDiffsDescription: 'Wrap long lines instead of horizontal scrolling in diff views',
        alwaysShowContextSize: 'Always Show Context Size',
        alwaysShowContextSizeDescription: 'Display context usage even when not near limit',
        avatarStyle: 'Avatar Style',
        avatarStyleDescription: 'Choose session avatar appearance',
        avatarOptions: {
            pixelated: 'Pixelated',
            gradient: 'Gradient',
            brutalist: 'Brutalist',
        },
        showFlavorIcons: 'Show AI Provider Icons',
        showFlavorIconsDescription: 'Display AI provider icons on session avatars',
        compactSessionView: 'Compact Session View',
        compactSessionViewDescription: 'Show active sessions in a more compact layout',
    },

    settingsFeatures: {
        // Features settings screen
        appExperience: 'App Experience',
        appExperienceDescription: 'Controls that affect browsing sessions and day-to-day interaction behavior.',
        experiments: 'Experiments',
        experimentsDescription: 'Enable experimental features that are still in development. These features may be unstable or change without notice.',
        experimentalFeatures: 'Experimental Features',
        experimentalFeaturesEnabled: 'Experimental features enabled',
        experimentalFeaturesDisabled: 'Using stable features only',
        markdownCopyV2: 'Markdown Copy v2',
        markdownCopyV2Subtitle: 'Long press opens copy modal',
        hideInactiveSessions: 'Hide inactive sessions',
        hideInactiveSessionsSubtitle: 'Show only active chats in your list',
        sessionReconnect: 'Session Reconnect',
        sessionReconnectSubtitle: 'Reconnect disconnected sessions through the machine daemon',
    },

    errors: {
        networkError: 'Network error occurred',
        serverError: 'Server error occurred',
        unknownError: 'An unknown error occurred',
        connectionTimeout: 'Connection timed out',
        authenticationFailed: 'Authentication failed',
        permissionDenied: 'Permission denied',
        fileNotFound: 'File not found',
        invalidFormat: 'Invalid format',
        operationFailed: 'Operation failed',
        tryAgain: 'Please try again',
        messageNotSentTitle: 'Message not sent',
        messageNotSentBody: 'A message is still sending in the background. It will fail in 30 seconds if not delivered.',
        messageFailedTitle: 'Message failed',
        messageFailedBody: 'A message failed to send while the app was in background. Open Orbit and retry.',
        backgroundSendFailedReason: 'Message failed to send in background after 30s. Please retry.',
        contactSupport: 'Contact support if the problem persists',
        sessionNotFound: 'Session not found',
        voiceSessionFailed: 'Failed to start voice session',
        voiceServiceUnavailable: 'Voice service is temporarily unavailable',
        voiceLimitReachedTitle: 'Voice Limit Reached',
        voiceHardLimitReached: ({ hours }: { hours: number }) => `You've used ${hours}+ hours of voice this month. This is the maximum allowed. You can configure your own ElevenLabs agent in Voice settings to use your own quota.`,
        voiceConversationLimitReached: 'You\'ve reached the maximum number of voice conversations this month. We may add on-demand voice usage in the future — please file an issue at github.com/wwq20030329-oss/orbit/issues if you hit this limit.',
        oauthInitializationFailed: 'Failed to initialize OAuth flow',
        tokenStorageFailed: 'Failed to store authentication tokens',
        oauthStateMismatch: 'Security validation failed. Please try again',
        tokenExchangeFailed: 'Failed to exchange authorization code',
        oauthAuthorizationDenied: 'Authorization was denied',
        webViewLoadFailed: 'Failed to load authentication page',
        failedToLoadProfile: 'Failed to load user profile',
        userNotFound: 'User not found',
        sessionDeleted: 'Session has been deleted',
        sessionDeletedDescription: 'This session has been permanently removed',

        // Error functions with context
        fieldError: ({ field, reason }: { field: string; reason: string }) =>
            `${field}: ${reason}`,
        validationError: ({ field, min, max }: { field: string; min: number; max: number }) =>
            `${field} must be between ${min} and ${max}`,
        retryIn: ({ seconds }: { seconds: number }) =>
            `Retry in ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
        errorWithCode: ({ message, code }: { message: string; code: number | string }) =>
            `${message} (Error ${code})`,
        disconnectServiceFailed: ({ service }: { service: string }) => 
            `Failed to disconnect ${service}`,
        connectServiceFailed: ({ service }: { service: string }) =>
            `Failed to connect ${service}. Please try again.`,
        failedToLoadFriends: 'Failed to load friends list',
        failedToAcceptRequest: 'Failed to accept friend request',
        failedToRejectRequest: 'Failed to reject friend request',
        failedToRemoveFriend: 'Failed to remove friend',
        searchFailed: 'Search failed. Please try again.',
        failedToSendRequest: 'Failed to send friend request',
    },

    newSession: {
        title: 'Start New Session',
        machineOffline: 'Machine is offline',
        switchMachinesHint: '• Switch machines by clicking on the machine above',
        quickMode: 'Quick Mode',
        expertMode: 'Expert Mode',
        quickModeTitle: 'Start with quick mode',
        expertModeTitle: 'Start with expert mode',
        quickModeSubtitle: 'Best for everyday work, with faster startup.',
        expertModeSubtitle: 'Review machine, project, and model choices before creating the session.',
        openAdvanced: 'Open advanced composer',
        machineLabel: 'Machine',
        projectLabel: 'Project',
        modeLabel: 'Mode',
        customPath: 'Custom path',
        recentProjects: 'Recent Projects',
        noRecentProjects: 'No recent projects yet',
        advancedSettings: 'Advanced',
        noMachineSelected: 'Select a machine first',
        messagePlaceholder: 'Send a message or press and hold to talk',
        createDirectoryTitle: 'Create Directory?',
        createDirectoryBody: ({ directory }: { directory: string }) => `The directory '${directory}' does not exist. Would you like to create it?`,
    },

    sessionHistory: {
        // Used by session history screen
        title: 'Session History',
        empty: 'No sessions found',
        today: 'Today',
        yesterday: 'Yesterday',
        daysAgo: ({ count }: { count: number }) => `${count} ${count === 1 ? 'day' : 'days'} ago`,
        viewAll: 'View all sessions',
        sessionsTab: 'Sessions',
        historyTab: 'History',
        currentProject: 'Current project',
        allProjects: 'All projects',
        sessionsCount: ({ count }: { count: number }) => `${count} sessions`,
        projectCount: ({ count }: { count: number }) => `${count} ${count === 1 ? 'project' : 'projects'}`,
        noWorkYet: ({ tool }: { tool: string }) => `No ${tool} work yet`,
        showMore: 'Show more',
        showLess: 'Show less',
        startSessionCompact: ({ tool }: { tool: string }) => `Start a ${tool} session on your computer and it will appear here.`,
        startSessionDetail: ({ tool }: { tool: string }) => `Start a ${tool} session on your computer, and it will show up here for quick continue.`,
        pinToDrawer: 'Pin to drawer',
        unpinFromDrawer: 'Unpin from drawer',
        removeFromDrawer: 'Hide from sidebar',
        drawerRemoveOnly: 'This only hides it from the quick sidebar. It stays available in Project Sessions.',
    },

    session: {
        inputPlaceholder: 'Type a message ...',
        inactiveArchived: 'This session is inactive.',
        resumeFromTerminal: 'To resume it from the terminal:',
        recoveredTitle: 'Recovered Session',
    },
    server: {
        // Used by Server Configuration screen (app/(app)/server.tsx)
        serverConfiguration: 'Server Configuration',
        enterServerUrl: 'Please enter a server URL',
        notValidOrbitServer: 'Not a valid Orbit Server',
        changeServer: 'Change Server',
        continueWithServer: 'Continue with this server?',
        resetToDefault: 'Reset to Default',
        resetServerDefault: 'Reset server to default?',
        validating: 'Validating...',
        validatingServer: 'Validating server...',
        serverReturnedError: 'Server returned an error',
        failedToConnectToServer: 'Failed to connect to server',
        currentlyUsingCustomServer: 'Currently using custom server',
        customServerUrlLabel: 'Custom Server URL',
        advancedFeatureFooter: "This is an advanced feature. Only change the server if you know what you're doing. You will need to log out and log in again after changing servers."
    },

    sessionInfo: {
        // Used by Session Info screen (app/(app)/session/[id]/info.tsx)
        killSession: 'Kill Session',
        killSessionConfirm: 'Are you sure you want to terminate this session?',
        archiveSession: 'Archive Session',
        archiveSessionConfirm: 'Are you sure you want to archive this session?',
        orbitSessionIdCopied: 'Orbit Session ID copied to clipboard',
        failedToCopySessionId: 'Failed to copy Orbit Session ID',
        orbitSessionId: 'Orbit Session ID',
        claudeCodeSessionId: 'Claude Code Session ID',
        claudeCodeSessionIdCopied: 'Claude Code Session ID copied to clipboard',
        codexThreadId: 'Codex Thread ID',
        codexThreadIdCopied: 'Codex Thread ID copied to clipboard',
        nativeCliSessionId: 'Native CLI Session ID',
        nativeCliSessionIdCopied: 'Native CLI Session ID copied to clipboard',
        aiProvider: 'AI Provider',
        failedToCopyClaudeCodeSessionId: 'Failed to copy Claude Code Session ID',
        failedToCopyCodexThreadId: 'Failed to copy Codex Thread ID',
        failedToCopyNativeCliSessionId: 'Failed to copy Native CLI Session ID',
        metadataCopied: 'Session metadata copied to clipboard',
        failedToCopyMetadata: 'Failed to copy session metadata',
        failedToKillSession: 'Failed to kill session',
        failedToArchiveSession: 'Failed to archive session',
        connectionStatus: 'Connection Status',
        created: 'Created',
        lastUpdated: 'Last Updated',
        sequence: 'Sequence',
        quickActions: 'Quick Actions',
        viewMachine: 'View Machine',
        viewMachineSubtitle: 'View machine details and sessions',
        resumeSession: 'Resume Session',
        resumeSessionSubtitle: 'Resume this session on the same machine',
        resumeSessionSameMachineOnly: 'This session can only be resumed on the same machine it started on.',
        resumeSessionMachineOffline: 'This machine is offline. Resume is only available while it is online.',
        resumeSessionNeedsOrbitAgent: 'Resume is unavailable on this machine. Run `orbit-agent auth login` to enable it.',
        resumeSessionMissingMachine: 'This session is missing its machine metadata, so it cannot be resumed.',
        resumeSessionMissingBackendId: 'This session does not have a resumable native CLI identifier.',
        resumeSessionUnexpectedDirectoryPrompt: 'Resume cannot create directories. Start the session manually from its original path.',
        killSessionSubtitle: 'Immediately terminate the session',
        archiveSessionSubtitle: 'Archive this session and stop it',
        metadata: 'Metadata',
        host: 'Host',
        path: 'Path',
        operatingSystem: 'Operating System',
        processId: 'Process ID',
        orbitHome: 'Orbit Home',
        copyMetadata: 'Copy session metadata',
        agentState: 'Agent State',
        controlledByUser: 'Controlled by User',
        pendingRequests: 'Pending Requests',
        activity: 'Activity',
        thinking: 'Thinking',
        thinkingSince: 'Thinking Since',
        cliVersion: 'CLI Version',
        cliVersionOutdated: 'CLI Update Required',
        cliVersionOutdatedMessage: ({ currentVersion, requiredVersion }: { currentVersion: string; requiredVersion: string }) =>
            `Version ${currentVersion} installed. Update to ${requiredVersion} or later`,
        updateCliInstructions: 'Please run npm install -g orbit@latest',
        deleteSession: 'Delete Session',
        deleteSessionSubtitle: 'Permanently remove this Orbit session',
        deleteSessionConfirm: 'Delete Session Permanently?',
        deleteSessionWarning: 'This action cannot be undone. Orbit will delete this session from your account.',
        failedToDeleteSession: 'Failed to delete session',
        sessionDeleted: 'Session deleted successfully',
        deleteProject: 'Delete Project',
        deleteProjectWarning: 'This action cannot be undone. Orbit will delete all Orbit sessions in this project.',
        failedToDeleteProject: 'Failed to delete project',
        projectDeleted: 'Project deleted successfully',
        worktreeCleanupTitle: 'Delete Worktree?',
        worktreeCleanupMessage: 'The worktree has no uncommitted changes. Would you like to delete the worktree files?',
        worktreeCleanupDelete: 'Delete Worktree',
        worktreeCleanupKeep: 'Keep Files',
        
    },

    components: {
        emptyMainScreen: {
            // Used by EmptyMainScreen component
            readyToCode: 'Ready to code?',
            installCli: 'Install the Orbit CLI',
            runIt: 'Run it',
            scanQrCode: 'Scan the QR code',
            openCamera: 'Open Camera',
        },
        emptySessionsTablet: {
            noActiveSessions: 'No active sessions',
            onlineDescription: 'Start a new session on any of your connected machines.',
            startNewSession: 'Start New Session',
            offlineDescription: 'Open a new terminal on your computer to start a session.',
        },
    },

    agentInput: {
        permissionMode: {
            title: 'PERMISSION MODE',
            default: 'default permissions',
            acceptEdits: 'accept edits',
            plan: 'plan',
            auto: 'auto',
            dontAsk: "don't ask",
            bypassPermissions: 'yolo',
            badgeAcceptAllEdits: 'accept all edits',
            badgeBypassAllPermissions: 'yolo',
            badgePlanMode: 'plan mode',
        },
        agent: {
            claude: 'Claude',
            codex: 'Codex',
            gemini: 'Gemini',
            openclaw: 'OpenClaw',
        },
        model: {
            title: 'MODEL',
            configureInCli: 'Configure models in CLI settings',
        },
        effort: {
            title: 'REASONING',
            auto: 'auto',
            none: 'none',
            minimal: 'minimal',
            low: 'low',
            medium: 'medium',
            high: 'high',
            xhigh: 'xhigh',
            max: 'max',
        },
        codexPermissionMode: {
            title: 'CODEX PERMISSION MODE',
            default: 'default permissions',
            readOnly: 'read-only',
            safeYolo: 'safe yolo',
            yolo: 'yolo',
            badgeReadOnly: 'read-only',
            badgeSafeYolo: 'safe yolo',
            badgeYolo: 'yolo',
        },
        codexModel: {
            title: 'CODEX MODEL',
            gpt5CodexLow: 'gpt-5-codex low',
            gpt5CodexMedium: 'gpt-5-codex medium',
            gpt5CodexHigh: 'gpt-5-codex high',
            gpt5Minimal: 'GPT-5 Minimal',
            gpt5Low: 'GPT-5 Low',
            gpt5Medium: 'GPT-5 Medium',
            gpt5High: 'GPT-5 High',
        },
        geminiPermissionMode: {
            title: 'GEMINI PERMISSION MODE',
            default: 'default permissions',
            autoEdit: 'auto edit',
            yolo: 'yolo',
            plan: 'plan',
            badgeAutoEdit: 'auto edit',
            badgeYolo: 'yolo',
            badgePlan: 'plan',
        },
        context: {
            remaining: ({ percent }: { percent: number }) => `${percent}% left`,
        },
        suggestion: {
            fileLabel: 'FILE',
            folderLabel: 'FOLDER',
        },
        noMachinesAvailable: 'No machines',
    },

    machineLauncher: {
        showLess: 'Show less',
        showAll: ({ count }: { count: number }) => `Show all (${count} paths)`,
        enterCustomPath: 'Enter custom path',
        offlineUnableToSpawn: 'Unable to spawn new session, offline',
    },

    sidebar: {
        sessionsTitle: 'Orbit',
    },

    toolView: {
        input: 'Input',
        output: 'Output',
    },

    tools: {
        fullView: {
            description: 'Description',
            inputParams: 'Input Parameters',
            output: 'Output',
            error: 'Error',
            completed: 'Tool completed successfully',
            noOutput: 'No output was produced',
            running: 'Tool is running...',
            rawJsonDevMode: 'Raw JSON (Dev Mode)',
        },
        taskView: {
            initializing: 'Initializing agent...',
            moreTools: ({ count }: { count: number }) => `+${count} more ${plural({ count, singular: 'tool', plural: 'tools' })}`,
        },
        multiEdit: {
            editNumber: ({ index, total }: { index: number; total: number }) => `Edit ${index} of ${total}`,
            replaceAll: 'Replace All',
        },
        names: {
            task: 'Task',
            terminal: 'Terminal',
            searchFiles: 'Search Files',
            search: 'Search',
            searchContent: 'Search Content',
            listFiles: 'List Files',
            planProposal: 'Plan proposal',
            readFile: 'Read File',
            editFile: 'Edit File',
            writeFile: 'Write File',
            fetchUrl: 'Fetch URL',
            readNotebook: 'Read Notebook',
            editNotebook: 'Edit Notebook',
            todoList: 'Todo List',
            webSearch: 'Web Search',
            reasoning: 'Reasoning',
            applyChanges: 'Update file',
            viewDiff: 'Current file changes',
            question: 'Question',
        },
        askUserQuestion: {
            submit: 'Submit Answer',
            multipleQuestions: ({ count }: { count: number }) => `${count} questions`,
            other: 'Other',
            otherDescription: 'Type your own answer',
            otherPlaceholder: 'Type your answer...',
        },
        desc: {
            terminalCmd: ({ cmd }: { cmd: string }) => `Terminal(cmd: ${cmd})`,
            searchPattern: ({ pattern }: { pattern: string }) => `Search(pattern: ${pattern})`,
            searchPath: ({ basename }: { basename: string }) => `Search(path: ${basename})`,
            fetchUrlHost: ({ host }: { host: string }) => `Fetch URL(url: ${host})`,
            editNotebookMode: ({ path, mode }: { path: string; mode: string }) => `Edit Notebook(file: ${path}, mode: ${mode})`,
            todoListCount: ({ count }: { count: number }) => `Todo List(count: ${count})`,
            webSearchQuery: ({ query }: { query: string }) => `Web Search(query: ${query})`,
            grepPattern: ({ pattern }: { pattern: string }) => `grep(pattern: ${pattern})`,
            multiEditEdits: ({ path, count }: { path: string; count: number }) => `${path} (${count} edits)`,
            readingFile: ({ file }: { file: string }) => `Reading ${file}`,
            writingFile: ({ file }: { file: string }) => `Writing ${file}`,
            modifyingFile: ({ file }: { file: string }) => `Modifying ${file}`,
            modifyingFiles: ({ count }: { count: number }) => `Modifying ${count} files`,
            modifyingMultipleFiles: ({ file, count }: { file: string; count: number }) => `${file} and ${count} more`,
            moreFiles: ({ count }: { count: number }) => `+${count} more files`,
            showingDiff: 'Showing changes',
        }
    },

    files: {
        searchPlaceholder: 'Search files...',
        detachedHead: 'detached HEAD',
        summary: ({ staged, unstaged }: { staged: number; unstaged: number }) => `${staged} staged • ${unstaged} unstaged`,
        notRepo: 'Not a git repository',
        notUnderGit: 'This directory is not under git version control',
        searching: 'Searching files...',
        noFilesFound: 'No files found',
        noFilesInProject: 'No files in project',
        tryDifferentTerm: 'Try a different search term',
        searchResults: ({ count }: { count: number }) => `Search Results (${count})`,
        projectRoot: 'Project root',
        stagedChanges: ({ count }: { count: number }) => `Staged Changes (${count})`,
        unstagedChanges: ({ count }: { count: number }) => `Unstaged Changes (${count})`,
        // File viewer strings
        loadingFile: ({ fileName }: { fileName: string }) => `Loading ${fileName}...`,
        binaryFile: 'Binary File',
        cannotDisplayBinary: 'Cannot display binary file content',
        diff: 'Diff',
        file: 'File',
        fileEmpty: 'File is empty',
        noChanges: 'No changes to display',
        deleted: 'Deleted',
    },

    settingsVoice: {
        // Voice settings screen
        languageTitle: 'Language',
        languageDescription: 'Choose your preferred language for voice assistant interactions. This setting syncs across all your devices.',
        preferredLanguage: 'Preferred Language',
        preferredLanguageSubtitle: 'Language used for voice assistant responses',
        language: {
            searchPlaceholder: 'Search languages...',
            title: 'Languages',
            footer: ({ count }: { count: number }) => `${count} ${plural({ count, singular: 'language', plural: 'languages' })} available`,
            autoDetect: 'Auto-detect',
            noResults: 'No matching languages',
        },
        // Bring your own agent
        byoTitle: 'Bring Your Own Agent',
        byoDescription: 'Use your own ElevenLabs agent instead of the Orbit default. No subscription required — connect directly with your own ElevenLabs account. Your agent must define two client tools: messageClaudeCode (sends text to the coding agent) and processPermissionRequest (allows or denies tool use). It receives session context via the {{initialConversationContext}} dynamic variable.',
        customAgentId: 'ElevenLabs Agent ID',
        customAgentIdNotSet: 'Not configured',
        customAgentIdDescription: 'Enter your ElevenLabs agent ID. Leave empty to use the Orbit default.',
        customAgentIdPlaceholder: 'e.g. abc123def456',
        bypassToken: 'Direct Connection',
        bypassTokenSubtitle: 'Skip Orbit server, connect straight to ElevenLabs',
        promptGuideTitle: 'Agent Prompt Guide',
        promptGuideDescription: 'Your ElevenLabs agent needs:\n\n• Tool: messageClaudeCode — parameter: message (string). Sends a message to the active coding session.\n• Tool: processPermissionRequest — parameter: decision ("allow" or "deny"). Approves or denies a pending tool permission.\n• Dynamic variable: {{initialConversationContext}} — receives session history and context on start.\n\nThe agent acts as a voice bridge between the user and coding agents. It should be concise, only respond when addressed, and report when a coding agent finishes work.',
        // Voice usage
        usageTitle: 'Usage (Last 30 Days)',
        usageFooter: 'Voice time used in the last 30 days. Free tier: 20 min. Subscribed: 5 hours. Max 100 conversations per month.',
        usageLabel: 'Voice Time',
        conversationsLabel: 'Conversations',
        usageUsed: ({ used, limit }: { used: string; limit: string }) => `${used} used of ${limit}`,
        supportTitle: 'Upgrade Voice',
        supportSubtitle: 'Get more voice time and support development',
        developerTitle: 'Developer',
        developerFooter: 'Developer-only diagnostics and local override controls for the current voice rollout. Orbit server remains the default paid voice gate unless direct connection and a custom ElevenLabs agent are both enabled.',
        developerOverrideTitle: 'Voice Rollout Override',
        developerOverrideSubtitle: 'Choose a local override for the current voice upsell flow.',
        developerStatusTitle: 'Current Rollout Status',
        developerResetCountersTitle: 'Reset Local Counters',
        developerResetCountersSubtitle: 'Clear this device\'s onboarding and soft-paywall counters.',
        developerNoOverride: 'No Override',
        developerControl: 'Control',
        developerSoftPaywall: 'Soft Paywall',
        developerOnboardingUpsell: 'Onboarding + Upsell',
        developerUpsellLine: ({ variant }: { variant: string }) => `Voice upsell: ${variant}`,
        developerSourceLine: ({ source }: { source: string }) => `Source: ${source}`,
        developerGateLine: ({ gate }: { gate: string }) => `Gate: ${gate}`,
        developerExperimentsLine: ({ enabled }: { enabled: boolean }) => `Experiments: ${enabled ? 'on' : 'off'}`,
        developerGateDirect: 'Direct BYO agent bypass',
        developerGateOrbit: 'Orbit server gate',
        developerCountersSoftPaywall: ({ count }: { count: number }) => `Soft paywall shown: ${count}`,
        developerCountersOnboarding: ({ count }: { count: number }) => `Onboarding prompt loads: ${count}`,
        developerCountersVoiceMessages: ({ count }: { count: number }) => `Voice messages: ${count}`,
    },

    voicePermissions: {
        accessRequiredTitle: 'Microphone Access Required',
        grantPrompt: 'Orbit needs access to your microphone for voice chat. Please grant permission when prompted.',
        openSettingsPrompt: 'Orbit needs access to your microphone for voice chat. Please enable microphone access in your device settings.',
        browserPrompt: 'Please allow microphone access in your browser settings. You may need to click the lock icon in the address bar and enable microphone permission for this site.',
    },

    settingsAccount: {
        // Account settings screen
        accountInformation: 'Account Information',
        status: 'Status',
        statusActive: 'Active',
        statusNotAuthenticated: 'Not Authenticated',
        anonymousId: 'Anonymous ID',
        publicId: 'Public ID',
        notAvailable: 'Not available',
        linkNewDevice: 'Link New Device',
        linkNewDeviceSubtitle: 'Scan QR code to link device',
        profile: 'Profile',
        name: 'Name',
        github: 'GitHub',
        tapToDisconnect: 'Tap to disconnect',
        server: 'Server',
        backup: 'Backup',
        backupDescription: 'Your secret key is the only way to recover your account. Save it in a secure place like a password manager.',
        secretKey: 'Secret Key',
        tapToReveal: 'Tap to reveal',
        tapToHide: 'Tap to hide',
        secretKeyLabel: 'SECRET KEY (TAP TO COPY)',
        secretKeyCopied: 'Secret key copied to clipboard. Store it in a safe place!',
        secretKeyCopyFailed: 'Failed to copy secret key',
        privacy: 'Privacy',
        privacyDescription: 'Help improve the app by sharing anonymous usage data. No personal information is collected.',
        analytics: 'Analytics',
        analyticsDisabled: 'No data is shared',
        analyticsEnabled: 'Anonymous usage data is shared',
        pushNotifications: 'Push Notifications',
        pushNotificationsFooter: 'Shows every push token registered on your account. Tap an old token to delete it.',
        pushPermissionTitle: 'Permission',
        pushPermissionUnavailable: 'Unavailable',
        pushPermissionAllowed: 'Allowed',
        pushPermissionDenied: 'Denied',
        pushPermissionNotRequested: 'Not requested',
        pushPermissionChecking: 'Checking push notification permissions for this device.',
        pushPermissionUnsupportedDescription: 'Push notification permissions are only managed on mobile devices.',
        pushPermissionGrantedDescription: 'This device can receive push notifications.',
        pushPermissionCanAskAgainDescription: 'The system prompt can still be shown again from the app.',
        pushPermissionOpenSettingsDescription: 'iOS has stopped prompting. Open system settings to enable notifications again.',
        pushRequestPermissionAgain: 'Request Permission Again',
        pushRequestPermissionUnsupportedSubtitle: 'Push notification permissions are only available on iPhone and Android.',
        pushRequestPermissionCanAskAgainSubtitle: 'Shows the system prompt again if iOS still allows it.',
        pushRequestPermissionOpenSettingsSubtitle: 'Opens system settings when iOS will not prompt again.',
        pushReregisterDevice: 'Re-register This Device',
        pushCurrentTokenSubtitle: ({ token }: { token: string }) => `Current token ${token}`,
        pushReregisterSubtitle: 'Fetches the current Expo token and registers it again.',
        pushRegisteredTokens: ({ count }: { count: number }) => `Registered Tokens (${count})`,
        pushRegisteredTokensFooter: 'Current-device metadata comes from this phone. Older tokens use their token fingerprint plus server timestamps.',
        pushNoRegisteredTokens: 'No registered push tokens',
        pushNoRegisteredTokensSubtitle: 'Once this device is registered, it will appear here.',
        pushThisDevice: 'This device',
        pushTokenOtherDevice: 'Other device or stale registration',
        pushTokenRegisteredAt: ({ time }: { time: string }) => `Registered: ${time}`,
        pushTokenLastSeen: ({ time }: { time: string }) => `Last seen: ${time}`,
        pushTokenServerId: ({ id }: { id: string }) => `Server ID: ${id}`,
        pushTokenFingerprint: ({ token }: { token: string }) => `Token: ${token}`,
        pushSettingsLoadFailed: 'Failed to load push notification settings.',
        pushPermissionEnabledSuccess: 'Push notifications are enabled for this device.',
        pushPermissionOpenedSettingsBody: 'The system will not show the permission prompt again, so Orbit opened Settings instead.',
        pushPermissionNotGranted: 'Push notification permission was not granted.',
        pushPermissionRequestFailed: 'Failed to request push notification permission.',
        pushCapabilityMissingBody: 'This build is missing the iOS Push Notifications capability. Reinstall the dev build from Xcode after enabling the push entitlement.',
        pushProjectIdMissingBody: 'This build is missing the Expo project ID required for push registration. Rebuild the app and try again.',
        pushRefreshDisabled: 'Push notifications are not enabled for this device yet.',
        pushRefreshSuccess: 'This device push token was refreshed.',
        pushRefreshFailed: 'Failed to refresh this device push token.',
        pushDeleteTokenTitle: 'Delete Push Token',
        pushDeleteTokenConfirm: ({ token }: { token: string }) => `Remove ${token} from your account?`,
        pushDeleteTokenFailed: 'Failed to delete push token.',
        dangerZone: 'Danger Zone',
        logout: 'Logout',
        logoutSubtitle: 'Sign out and clear local data',
        logoutConfirm: 'Are you sure you want to logout? Make sure you have backed up your secret key!',
        deleteAccount: 'Delete Account',
        deleteAccountSubtitle: 'Permanently remove your account and all data',
        deleteAccountConfirm: 'Are you sure you want to delete your account? This action cannot be undone. All your data will be permanently removed.',
    },

    devTools: {
        appInformation: 'App Information',
        buildNumber: 'Build Number',
        sdkVersion: 'SDK Version',
        platform: 'Platform',
        anonymousId: 'Anonymous ID',
        debugOptions: 'Debug Options',
        debugMode: 'Debug Mode',
        consoleOutput: 'Console Output',
        consoleOutputSubtitle: 'Enable console output in production builds',
        verboseLogging: 'Verbose Logging',
        verboseLoggingSubtitle: 'Log all network requests and responses',
        viewLogs: 'View Logs',
        componentDemos: 'Component Demos',
        deviceInfo: 'Device Info',
        deviceInfoSubtitle: 'Safe area insets and device parameters',
        listComponents: 'List Components',
        listComponentsSubtitle: 'Demo of Item, ItemGroup, and ItemList',
        listComponentsDemo: 'List Components Demo',
        typography: 'Typography',
        typographySubtitle: 'All typography styles',
        colors: 'Colors',
        colorsSubtitle: 'Color palette and themes',
        messageDemos: 'Message Demos',
        messageDemosSubtitle: 'Various message types and components',
        invertedListTest: 'Inverted List Test',
        invertedListTestSubtitle: 'Test inverted FlatList with keyboard',
        toolViews: 'Tool Views',
        toolViewsSubtitle: 'Tool call visualization components',
        toolViewsDemo: 'Tool Views Demo',
        shimmerView: 'Shimmer View',
        shimmerViewSubtitle: 'Shimmer loading effects with masks',
        shimmerViewDemo: 'Shimmer View Demo',
        multiTextInput: 'Multi Text Input',
        multiTextInputSubtitle: 'Auto-growing multiline text input',
        inputStyles: 'Input Styles',
        inputStylesSubtitle: '10+ different input field style variants',
        modalSystem: 'Modal System',
        modalSystemSubtitle: 'Alert, confirm, and custom modals',
        unitTests: 'Unit Tests',
        unitTestsSubtitle: 'Run tests in the app environment',
        unistylesDemo: 'Unistyles Demo',
        unistylesDemoSubtitle: 'React Native Unistyles features and capabilities',
        qrCodeTest: 'QR Code Test',
        qrCodeTestSubtitle: 'Test QR code generation with different parameters',
        sessionComposer: 'Session Composer',
        sessionComposerSubtitle: 'New session creation screen layout',
        testFeatures: 'Test Features',
        testFeaturesFooter: 'These actions may affect app stability',
        testCrash: 'Test Crash',
        testCrashSubtitle: 'Trigger a test crash',
        testCrashConfirmTitle: 'Test Crash',
        testCrashConfirmBody: 'This will crash the app. Continue?',
        testCrashConfirmAction: 'Crash',
        clearCache: 'Clear Cache',
        clearCacheSubtitle: 'Remove all cached data',
        clearCacheConfirmTitle: 'Clear Cache',
        clearCacheConfirmBody: 'Are you sure you want to clear all cached data?',
        clearCacheConfirmAction: 'Clear',
        clearCacheSuccess: 'Cache has been cleared',
        resetChangelog: 'Reset Changelog',
        resetChangelogSubtitle: 'Show "What\'s New" banner again',
        resetChangelogSuccess: 'Changelog reset. Restart app to see the banner.',
        resetAppState: 'Reset App State',
        resetAppStateSubtitle: 'Clear all user data and preferences',
        resetAppStateConfirmTitle: 'Reset App',
        resetAppStateConfirmBody: 'This will delete all data. Are you sure?',
        resetAppStateConfirmAction: 'Reset',
        system: 'System',
        purchases: 'Purchases',
        purchasesSubtitle: 'View subscriptions and entitlements',
        expoConstants: 'Expo Constants',
        expoConstantsSubtitle: 'View expoConfig, manifests, and system constants',
        network: 'Network',
        apiEndpoint: 'API Endpoint',
        apiEndpointSubtitle: 'Bundled at build time and no longer editable on-device',
        logServer: 'Log Server',
        logServerSubtitle: 'Sends unencrypted console logs over HTTP',
        logServerPromptTitle: 'Remote Log Server',
        logServerPromptBody: 'Sends ALL console output as unencrypted plaintext over HTTP to this URL. Use your Mac\'s local IP (e.g. http://192.168.1.5:8787). Run "yarn app-logs" on your Mac to receive. Clear to disable.',
        logServerDisabled: 'Remote logging disabled. Restart app for changes to take effect.',
        logServerUpdated: 'Log server URL updated. Restart app for changes to take effect.',
        invalidUrlTitle: 'Invalid URL',
        invalidUrlBody: 'Please enter a valid URL',
        socketStatus: 'Socket.IO Status',
        socketConnectedAgo: ({ time }: { time: string }) => `Connected ${time}`,
        socketLastConnectedAgo: ({ time }: { time: string }) => `Last connected ${time}`,
        socketConnecting: 'Connecting to server...',
        socketNoInfo: 'No connection info',
        off: 'Off',
        logsTitle: ({ count }: { count: number }) => `Logs (${count})`,
        logsFooter: ({ count }: { count: string }) => `Stored locally and capped at ${count} entries. Oldest logs are dropped first.`,
        addTestLog: 'Add Test Log',
        addTestLogSubtitle: 'Add a test log entry with timestamp',
        copyAllLogs: 'Copy All Logs',
        clearAllLogs: 'Clear All Logs',
        clearLogsConfirmTitle: 'Clear Logs',
        clearLogsConfirmBody: 'Are you sure you want to clear all logs?',
        clearLogsConfirmAction: 'Clear',
        noLogsTitle: 'No Logs',
        noLogsToCopy: 'There are no logs to copy',
        logsCopied: ({ count }: { count: number }) => `${count} log entries copied to clipboard`,
        noLogsYet: 'No logs yet',
        noLogsYetSubtitle: 'Logs will appear here as they are generated',
        deviceInfoTitle: 'Device Info',
        safeAreaInsets: 'Safe Area Insets',
        top: 'Top',
        bottom: 'Bottom',
        left: 'Left',
        right: 'Right',
        deviceDetection: 'Device Detection',
        deviceTypeTitle: 'Device Type',
        tablet: 'Tablet',
        phone: 'Phone',
        detectionMethod: 'Detection Method',
        macCatalyst: 'Mac Catalyst',
        headerHeight: 'Header Height',
        diagonalSize: 'Diagonal Size',
        widthInches: 'Width (inches)',
        heightInches: 'Height (inches)',
        pixelDensity: 'Pixel Density',
        pointsPerInch: 'Points per Inch',
        layoutMaxWidth: 'Layout Max Width',
        screenDimensions: 'Screen Dimensions',
        windowWidth: 'Window Width',
        windowHeight: 'Window Height',
        screenWidth: 'Screen Width',
        screenHeight: 'Screen Height',
        physicalPixelsWidth: 'Physical Pixels (width)',
        physicalPixelsHeight: 'Physical Pixels (height)',
        aspectRatio: 'Aspect Ratio',
        platformInfo: 'Platform Info',
        version: 'Version',
        iosInterface: 'iOS Interface',
        iosVersion: 'iOS Version',
        apiLevel: 'API Level',
        appInfo: 'App Info',
        appVersion: 'App Version',
        notAvailable: 'Not available',
        pointsValue: ({ value }: { value: string }) => `${value} points`,
        inchesValue: ({ value }: { value: string }) => `${value} inches`,
        diagonalValue: ({ value }: { value: string }) => `${value} diagonal`,
        expoConstantsTitle: 'Expo Constants',
        jsonCopied: 'JSON data copied to clipboard',
        failedToCopyJson: 'Failed to copy to clipboard',
        configurationFromConstantsApi: 'Configuration from Constants API',
        rawNativeModuleManifests: 'Raw Native Module Manifests',
        rawManifestStrings: 'Raw Manifest Strings',
        resolvedAppConfig: 'Resolved App Config',
        systemConstants: 'System Constants',
        updatesInformation: 'Updates Information',
        platformConstants: 'Platform Constants',
        systemFonts: 'System Fonts',
        nativeModules: 'Native Modules',
        allConstantsDebug: 'All Constants (Debug)',
        isEmbeddedLaunch: 'Is Embedded Launch',
        loadedAppConfig: 'Loaded App Config (from @/config)',
    },

    settingsLanguage: {
        // Language settings screen
        title: 'Language',
        description: 'Choose your preferred language for the app interface. This will sync across all your devices.',
        currentLanguage: 'Current Language',
        automatic: 'Automatic',
        automaticSubtitle: 'Detect from device settings',
        needsRestart: 'Language Changed',
        needsRestartMessage: 'The app needs to restart to apply the new language setting.',
        restartNow: 'Restart Now',
    },

    connectButton: {
        authenticate: 'Authenticate Terminal',
        authenticateWithUrlPaste: 'Authenticate Terminal with URL paste',
        pasteAuthUrl: 'Paste the auth URL from your terminal',
    },

    updateBanner: {
        updateAvailable: 'Update available',
        pressToApply: 'Press to apply the update',
        whatsNew: "What's new",
        seeLatest: 'See the latest updates and improvements',
        nativeUpdateAvailable: 'App Update Available',
        tapToUpdateAppStore: 'Tap to update in App Store',
        tapToUpdatePlayStore: 'Tap to update in Play Store',
    },

    changelog: {
        // Used by the changelog screen
        version: ({ version }: { version: number }) => `Version ${version}`,
        noEntriesAvailable: 'No changelog entries available.',
    },

    terminal: {
        // Used by terminal connection screens
        webBrowserRequired: 'Web Browser Required',
        webBrowserRequiredDescription: 'Terminal connection links can only be opened in a web browser for security reasons. Please use the QR code scanner or open this link on a computer.',
        processingConnection: 'Processing connection...',
        invalidConnectionLink: 'Invalid Connection Link',
        invalidConnectionLinkDescription: 'The connection link is missing or invalid. Please check the URL and try again.',
        connectTerminal: 'Connect Terminal',
        terminalRequestDescription: 'A terminal is requesting to connect to your Orbit account. This will allow the terminal to send and receive messages securely.',
        connectionDetails: 'Connection Details',
        publicKey: 'Public Key',
        encryption: 'Encryption',
        endToEndEncrypted: 'End-to-end encrypted',
        acceptConnection: 'Accept Connection',
        connecting: 'Connecting...',
        reject: 'Reject',
        security: 'Security',
        securityFooter: 'This connection link was processed securely in your browser and was never sent to any server. Your private data will remain secure and only you can decrypt the messages.',
        securityFooterDevice: 'This connection was processed securely on your device and was never sent to any server. Your private data will remain secure and only you can decrypt the messages.',
        clientSideProcessing: 'Client-Side Processing',
        linkProcessedLocally: 'Link processed locally in browser',
        linkProcessedOnDevice: 'Link processed locally on device',
    },

    modals: {
        // Used across connect flows and settings
        authenticateTerminal: 'Authenticate Terminal',
        pasteUrlFromTerminal: 'Paste the authentication URL from your terminal',
        deviceLinkedSuccessfully: 'Device linked successfully',
        terminalConnectedSuccessfully: 'Terminal connected successfully',
        invalidAuthUrl: 'Invalid authentication URL',
        developerMode: 'Developer Mode',
        developerModeEnabled: 'Developer mode enabled',
        developerModeDisabled: 'Developer mode disabled',
        disconnectService: ({ service }: { service: string }) => 
            `Disconnect ${service}`,
        disconnectServiceConfirm: ({ service }: { service: string }) => 
            `Are you sure you want to disconnect ${service} from your account?`,
        disconnect: 'Disconnect',
        failedToConnectTerminal: 'Failed to connect terminal',
        cameraPermissionsRequiredToConnectTerminal: 'Camera permissions are required to connect terminal',
        failedToLinkDevice: 'Failed to link device',
        cameraPermissionsRequiredToScanQr: 'Camera permissions are required to scan QR codes'
    },

    navigation: {
        // Navigation titles and screen headers
        connectTerminal: 'Connect Terminal',
        linkNewDevice: 'Link New Device', 
        restoreWithSecretKey: 'Restore with Secret Key',
        whatsNew: "What's New",
        friends: 'Friends',
    },

    welcome: {
        // Main welcome screen for unauthenticated users
        title: 'Codex and Claude Code mobile client',
        subtitle: 'End-to-end encrypted and your account is stored only on your device.',
        createAccount: 'Create account',
        linkOrRestoreAccount: 'Link or restore account',
        loginWithMobileApp: 'Login with mobile app',
    },

    review: {
        // Used by utils/requestReview.ts
        enjoyingApp: 'Enjoying the app?',
        feedbackPrompt: "We'd love to hear your feedback!",
        yesILoveIt: 'Yes, I love it!',
        notReally: 'Not really'
    },

    items: {
        // Used by Item component for copy toast
        copiedToClipboard: ({ label }: { label: string }) => `${label} copied to clipboard`
    },

    machine: {
        launchNewSessionInDirectory: 'Launch New Session in Directory',
        offlineUnableToSpawn: 'Launcher disabled while machine is offline',
        offlineHelp: '• Make sure your computer is online\n• Run `orbit daemon status` to diagnose\n• Are you running the latest CLI version? Upgrade with `npm install -g orbit@latest`',
        daemon: 'Daemon',
        status: 'Status',
        stopDaemon: 'Stop Daemon',
        lastKnownPid: 'Last Known PID',
        lastKnownHttpPort: 'Last Known HTTP Port',
        startedAt: 'Started At',
        cliVersion: 'CLI Version',
        daemonStateVersion: 'Daemon State Version',
        activeSessions: ({ count }: { count: number }) => `Active Sessions (${count})`,
        machineGroup: 'Machine',
        host: 'Host',
        machineId: 'Machine ID',
        username: 'Username',
        homeDirectory: 'Home Directory',
        platform: 'Platform',
        architecture: 'Architecture',
        lastSeen: 'Last Seen',
        never: 'Never',
        metadataVersion: 'Metadata Version',
        cliAvailability: 'CLI Availability',
        cliInstalled: 'Installed',
        cliNotFound: 'Not found',
        lastDetected: 'Last Detected',
        untitledSession: 'Untitled Session',
        back: 'Back',
    },

    message: {
        switchedToMode: ({ mode }: { mode: string }) => `Switched to ${mode} mode`,
        unknownEvent: 'Unknown event',
        usageLimitUntil: ({ time }: { time: string }) => `Usage limit reached until ${time}`,
        unknownTime: 'unknown time',
    },

    codex: {
        // Codex permission dialog buttons
        permissions: {
            yesForSession: "Yes, and don't ask for a session",
            stopAndExplain: 'Stop, and explain what to do',
        }
    },

    claude: {
        // Claude permission dialog buttons
        permissions: {
            yesAllowAllEdits: 'Yes, allow all edits during this session',
            yesForTool: "Yes, don't ask again for this tool",
            noTellClaude: 'No, and provide feedback',
        }
    },

    textSelection: {
        // Text selection screen
        selectText: 'Select text range',
        title: 'Select Text',
        noTextProvided: 'No text provided',
        textNotFound: 'Text not found or expired',
        textCopied: 'Text copied to clipboard',
        failedToCopy: 'Failed to copy text to clipboard',
        noTextToCopy: 'No text available to copy',
    },

    markdown: {
        // Markdown copy functionality
        codeCopied: 'Code copied',
        copyFailed: 'Copy failed',
        mermaidRenderFailed: 'Failed to render mermaid diagram',
    },

    artifacts: {
        // Artifacts feature
        title: 'Artifacts',
        countSingular: '1 artifact',
        countPlural: ({ count }: { count: number }) => `${count} artifacts`,
        empty: 'No artifacts yet',
        emptyDescription: 'Create your first artifact to get started',
        new: 'New Artifact',
        edit: 'Edit Artifact',
        delete: 'Delete',
        updateError: 'Failed to update artifact. Please try again.',
        notFound: 'Artifact not found',
        discardChanges: 'Discard changes?',
        discardChangesDescription: 'You have unsaved changes. Are you sure you want to discard them?',
        deleteConfirm: 'Delete artifact?',
        deleteConfirmDescription: 'This action cannot be undone',
        titleLabel: 'TITLE',
        titlePlaceholder: 'Enter a title for your artifact',
        bodyLabel: 'CONTENT',
        bodyPlaceholder: 'Write your content here...',
        emptyFieldsError: 'Please enter a title or content',
        createError: 'Failed to create artifact. Please try again.',
        save: 'Save',
        saving: 'Saving...',
        loading: 'Loading artifacts...',
        error: 'Failed to load artifact',
    },

    friends: {
        // Friends feature
        title: 'Friends',
        manageFriends: 'Manage your friends and connections',
        searchTitle: 'Find Friends',
        pendingRequests: 'Friend Requests',
        myFriends: 'My Friends',
        noFriendsYet: "You don't have any friends yet",
        findFriends: 'Find Friends',
        remove: 'Remove',
        pendingRequest: 'Pending',
        sentOn: ({ date }: { date: string }) => `Sent on ${date}`,
        accept: 'Accept',
        reject: 'Reject',
        addFriend: 'Add Friend',
        alreadyFriends: 'Already Friends',
        requestPending: 'Request Pending',
        searchInstructions: 'Enter a username to search for friends',
        searchPlaceholder: 'Enter username...',
        searching: 'Searching...',
        userNotFound: 'User not found',
        noUserFound: 'No user found with that username',
        checkUsername: 'Please check the username and try again',
        howToFind: 'How to Find Friends',
        findInstructions: 'Search for friends by their username. Both you and your friend need to have GitHub connected to send friend requests.',
        requestSent: 'Friend request sent!',
        requestAccepted: 'Friend request accepted!',
        requestRejected: 'Friend request rejected',
        friendRemoved: 'Friend removed',
        confirmRemove: 'Remove Friend',
        confirmRemoveMessage: 'Are you sure you want to remove this friend?',
        cannotAddYourself: 'You cannot send a friend request to yourself',
        bothMustHaveGithub: 'Both users must have GitHub connected to become friends',
        status: {
            none: 'Not connected',
            requested: 'Request sent',
            pending: 'Request pending',
            friend: 'Friends',
            rejected: 'Rejected',
        },
        acceptRequest: 'Accept Request',
        removeFriend: 'Remove Friend',
        removeFriendConfirm: ({ name }: { name: string }) => `Are you sure you want to remove ${name} as a friend?`,
        requestSentDescription: ({ name }: { name: string }) => `Your friend request has been sent to ${name}`,
        requestFriendship: 'Request friendship',
        cancelRequest: 'Cancel friendship request',
        cancelRequestConfirm: ({ name }: { name: string }) => `Cancel your friendship request to ${name}?`,
        denyRequest: 'Deny friendship',
        nowFriendsWith: ({ name }: { name: string }) => `You are now friends with ${name}`,
    },

    usage: {
        // Usage panel strings
        today: 'Today',
        last7Days: 'Last 7 days',
        last30Days: 'Last 30 days',
        totalTokens: 'Total Tokens',
        totalCost: 'Total Cost',
        tokens: 'Tokens',
        cost: 'Cost',
        usageOverTime: 'Usage over time',
        byModel: 'By Model',
        noData: 'No usage data available',
    },

    feed: {
        // Feed notifications for friend requests and acceptances
        friendRequestFrom: ({ name }: { name: string }) => `${name} sent you a friend request`,
        friendRequestGeneric: 'New friend request',
        friendAccepted: ({ name }: { name: string }) => `You are now friends with ${name}`,
        friendAcceptedGeneric: 'Friend request accepted',
    },

} as const;

export type Translations = typeof en;

/**
 * Generic translation type that matches the structure of Translations
 * but allows different string values (for other languages)
 */
export type TranslationStructure = {
    readonly [K in keyof Translations]: {
        readonly [P in keyof Translations[K]]: Translations[K][P] extends string 
            ? string 
            : Translations[K][P] extends (...args: any[]) => string 
                ? Translations[K][P] 
                : Translations[K][P] extends object
                    ? {
                        readonly [Q in keyof Translations[K][P]]: Translations[K][P][Q] extends string
                            ? string
                            : Translations[K][P][Q]
                      }
                    : Translations[K][P]
    }
};
